### ISSUE TITLE
config bombs

### ISSUE THREAD

**Issue by shinycolororange** [Pandarix/BetterArcheology#108]
allow bombs to disable terrain damage

**Comment by Pandarix** [comment]
I added this in the [new Multiloader Port of BA](https://github.com/Pandarix/BetterArcheology-MultiLoaded) in [this commit](https://github.com/Pandarix/BetterArcheology-MultiLoaded/commit/326a6ab920e3e3e363cbdee68ecd8293fc22fda8). This will hopefully release this weekend :).

Thank you for the suggestion!

**Comment by Pandarix** [comment]
Newest version is out now!

[![Modrinth](https://img.shields.io/modrinth/v/zCh7omyG?style=flat&logo=modrinth&logoColor=forestgreen&label=newest%3A&labelColor=black&color=forestgreen)](https://modrinth.com/mod/better-archeology)
[![CurseForge](https://img.shields.io/curseforge/v/835687?style=flat&logo=curseforge&logoColor=orangered&label=newest%3A&labelColor=black&color=orangered)](https://www.curseforge.com/minecraft/mc-mods/better-archeology)
