### ISSUE TITLE
Netherite Brush burns in lava

### ISSUE THREAD

**Issue by Qwerty97475** [Pandarix/BetterArcheology#110]
It shouldn't burn in lava, as in Minecraft, anything made of Netherite is lavaproof

**Comment by Pandarix** [comment]
You are very right, that must be an oversight. Sorry for the inconvenience!

**Comment by Pandarix** [comment]
This was already fixed a week ago on [the new Multiloader Port](https://github.com/Pandarix/BetterArcheology-MultiLoaded). The port will hopefully release on the weekend :)

**Comment by Pandarix** [comment]
Newest version is out now!

[![Modrinth](https://img.shields.io/modrinth/v/zCh7omyG?style=flat&logo=modrinth&logoColor=forestgreen&label=newest%3A&labelColor=black&color=forestgreen)](https://modrinth.com/mod/better-archeology)
[![CurseForge](https://img.shields.io/curseforge/v/835687?style=flat&logo=curseforge&logoColor=orangered&label=newest%3A&labelColor=black&color=orangered)](https://www.curseforge.com/minecraft/mc-mods/better-archeology)
