### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by aveinzero** [Pandarix/BetterArcheology#15]
![image](https://github.com/Pandarix/BetterArcheology/assets/99594631/9e32d04c-ac57-4805-9784-deb49ee9de46)

**Comment by Pandarix** [comment]
The fix will be uploaded in the next update that's coming soon.
Ty for reporting it ^^!

**Comment by Pandarix** [comment]
Fixed in `Better Archeology 1.0.1 for 1.20`.
See [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/better-archeology/files/4582508) or [Modrinth](https://modrinth.com/mod/better-archeology/version/sXGr31Up) once review is done.
