### ISSUE TITLE
Modrinth has the wrong links

### ISSUE THREAD

**Issue by aveinzero** [Pandarix/BetterArcheology#16]
![image](https://github.com/Pandarix/BetterArcheology/assets/99594631/1d0a8863-fd40-4fa0-a1bc-bacd9a07b1b8)
Everything redirects to BushyFlowers

**Comment by Pandarix** [comment]
<img width="627" alt="image" src="https://github.com/Pandarix/BetterArcheology/assets/98489042/62e70b76-9e7b-473d-9613-22f042777a0e">


fixed now, thanks for reporting!
