### ISSUE TITLE
Dispensers only drop bombs

### ISSUE THREAD

**Issue by LordGriefington** [Pandarix/BetterArcheology#24]
dipensers do the same as droppers. they should "throw" the rusty bombs. got me off guard after testing my cannon. I check if I used a dropper but it is definetley a dipenser.

also please keep the sytem that the projectiles share the item model. it allows me to use custom cit model based on name.

love the other features, should be it the game.

Im using fabric 0.14.21, fabric api 0.86.0 mc 1.20.1

**Comment by WorldsOfRosefire** [comment]
yes! can you make the bombs shooting from a dispenser? the act the same a dropper.
I can understand why though, because of griefing.
my suggestion, can you add a line the configs like dispenser.shooting=true
please

**Comment by Pandarix** [comment]
Added in [commit 69faeef](https://github.com/Pandarix/BetterArcheology/commit/69faeef420496f2bd6e21fe00a4032a34ed2a644)
Good suggestion! Did not think of that :). Will be added in version 1.1.1
