### ISSUE TITLE
Crash with CCME MC-1.20.1

### ISSUE THREAD

**Issue by samos667** [Pandarix/BetterArcheology#26]
Game crash when exploring world with [CCME](https://github.com/RelativityMC/C2ME-fabric) mod:

```[00:44:03] [C2ME worker #3/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_18028(class_2794.java:579)
[00:44:03] [C2ME worker #3/INFO]: [STDERR]: 	at 
net.Pandarix.betterarcheology.structures.ModStructures.extraSpawningChecks(ModStructures.java:89)
[00:44:03] [C2ME worker #3/INFO]: [STDERR]: 	at 
net.Pandarix.betterarcheology.structures.ModStructures.method_38676(ModStructures.java:102)
```
CCME greatly improve chunk generation and loading.

Would it be possible to make it compatible with it ?

[Full logs](https://mclo.gs/oWoYZRS) crash log start at line 2480.

**Comment by Pandarix** [comment]
Closing this issue because the CCME mod seems to be the incompatible mod.
The log shows that other worldgen features "terrestria" are also being blocked
