### ISSUE TITLE
Compatibility with tectonic 

### ISSUE THREAD

**Issue by benio1394** [Pandarix/BetterArcheology#31]
Hello, I want to suggest improving terrain generation with tectonic. Unfortunably structures from better archeology doesn't fit to this terrain generator creating structures based on vanilla generator.

![image](https://github.com/Pandarix/BetterArcheology/assets/51888209/5ad9275e-b049-4902-9d9e-9af178c84e32
  
This is example picture of underground ruins

**Comment by MokahTGS** [comment]
I second this request!

**Comment by Pandarix** [comment]
Thank you very much for reporting this issue.
I have gotten quite caught up recently and came back to this issue on [issue #40](https://github.com/Pandarix/BetterArcheology/issues/40).
For convenience’s sake, I will continue this discussion there. You are welcome to continue posting there :).
Sorry for the long wait!
