### ISSUE TITLE
Modpack: Penetrating Strike only applies to Axes

### ISSUE THREAD

**Issue by Th4V7** [Pandarix/BetterArcheology#33]
First off, I tested with only this mod and penetrating strike applied correctly to both swords and axes, so this may be beyond your scope.

I am playing a custom modpack and was unable to apply penetrating strike to a sword. It does applies correctly to axes however. Looking at "src/main/java/net/Pandarix/betterarcheology/enchantment/PenetratingStrikeEnchantment.java", the EnchantmentTarget line you use is distinct from all the other working enchants in the modpack: the others using EnchantmentCategory or specifically defining instanceof. Not having made a mod myself, is there a benefit to EnchantmentTarget or could EnchantmentCategory fix my issue?

Thanks for making this modpack, the chicken skeleton being a dinosaur and the ocelot being a saber tooth made me laugh.

**Comment by Pandarix** [comment]
Corrected in [commit a1cd77a](https://github.com/Pandarix/BetterArcheology/commit/a1cd77af2fd105ba85169d9cf87afa7a6d5ac344)
Will be added in 1.1.1.
Thanks for reporting!
