### ISSUE TITLE
Crash on using the Better Brush item on a non-suspicious block.

### ISSUE THREAD

**Issue by happyburger23** [Pandarix/BetterArcheology#34]
[crash-2023-12-03_19.36.44-client.txt](https://github.com/Pandarix/BetterArcheology/files/13540803/crash-2023-12-03_19.36.44-client.txt)

**Comment by Pandarix** [comment]
You were using the 1.20.1 Version of Minecraft 1.20.2
This issue is resolved in the newest version, which will be available once they're verified here:

https://modrinth.com/mod/better-archeology/version/oYXfn8Ly
https://legacy.curseforge.com/minecraft/mc-mods/better-archeology/files/4926931
