### ISSUE TITLE
Mining cracked mud bricks doesn't yield 

### ISSUE THREAD

**Issue by CadenCorvids** [Pandarix/BetterArcheology#36]
When I mine the cracked mud bricks in survival, the bricks do not drop. Video attached.

https://youtu.be/-QMZ6VW1_N0

**Comment by Pandarix** [comment]
I'll look into that. The issue should be relatively simple

**Comment by Pandarix** [comment]
fixed in [commit e698002](https://github.com/Pandarix/BetterArcheology/commit/e6980025628d8ef9795e80995b576700643ead5a)
Will be released in version 1.1.1 alongside other fixes very soon.
Thank you for reporting!
