### ISSUE TITLE
Catacomb spawners don't spawn mobs

### ISSUE THREAD

**Issue by generikb** [Pandarix/BetterArcheology#42]
Yo Pandarix!

We've included Better Archeology in our upcoming 1.20.1 Forge Modpack, and have noticed that the spawners in the new catacomb don't actually spawn any mobs, and it appears it's simply because there's always light sources too close:

![image](https://github.com/Pandarix/BetterArcheology/assets/41623747/7b3e4209-d352-44b6-8f64-d17e853c1458)

If you could fix that in a future update, that'd be amazing! thank you very much for the great mod!

Generikb

**Comment by Pandarix** [comment]
Hi Generikb, it is an honor!
This was a quick fix and is resolved in the version 1.1.1 alongside other small things.
There were 3 instances of this being an issue. Thanks for the feedback!

Once verification is done, 1.1.1 will be available on:
[CurseForge](https://curseforge.com/minecraft/mc-mods/better-archeology/files/5008773)
[Modrinth](https://modrinth.com/mod/better-archeology/version/1.1.1-1.20.1)
