### ISSUE TITLE
Several Underground structures contain waterlogged blocks (Flooded structures)

### ISSUE THREAD

**Issue by generikb** [Pandarix/BetterArcheology#43]
Yo again!

So this issue is pretty common among underground structures, but a lot of times blocks that *can* be waterlogged (stairs tend to get hit most often) end up rendering as waterlogged, which end up flooding/ruining the entire structure.  See photos below:

![image](https://github.com/Pandarix/BetterArcheology/assets/41623747/7b96ef31-5a18-4de9-9f4d-8b2e90dbd760)

![image](https://github.com/Pandarix/BetterArcheology/assets/41623747/24989f76-190a-4ad8-9238-7f1017da18e6)

I've had this discussion before with one of Yung's structures, and he uses a "tagging processor + mixin" to address it.  I apologize for not knowing what that *is* haha, but you could ask him if you needed help addressing the issue.

Thanks again!

Generikb

**Comment by Pandarix** [comment]
Hi again!

This is an issue that has bothered me for a long while myself.
Thank you very much for directing me to a possible solution, as I haven't found one myself yet!
I will definitely look into how Yung implemented it asap and will keep you updated.

**Comment by Pandarix** [comment]
Dropping this here for future reference and other people interested in resolving this issue:
[YUNGs-Better-Strongholds - WaterloggedProcessor.java](https://github.com/YUNG-GANG/YUNGs-Better-Strongholds/blob/1.20/Common/src/main/java/com/yungnickyoung/minecraft/betterstrongholds/world/processor/WaterloggedProcessor.java)

**Comment by Pandarix** [comment]
Alright. The fix you recommended was really really good and worked like a charm!
From version 1.1.2 on, the mod will depend on [YungsApi](https://www.curseforge.com/minecraft/mc-mods/yungs-api) 4.0.2 if you haven't already installed it.

Once verification is done, the fixed version will be available on:
- [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/better-archeology/files/5012093)
- [Modrinth](https://modrinth.com/mod/better-archeology/version/1.1.2-1.20.1)

Please let me know if everything is working :)

**Comment by generikb** [comment]
Heck ya, thanks so much!!!
