### ISSUE TITLE
[Bug] Archaeology table doesn't drop

### ISSUE THREAD

**Issue by JensenJ** [Pandarix/BetterArcheology#49]
When you break the archaeology table with an axe it does not drop its self. I had a look and it seems that no loot table exists for it. Using version 1.1.2 for 1.20.1 in our world.

**Comment by Pandarix** [comment]
I don't even know how this got through testing but you're right.
I'll fix it asap. There's an update coming out soon anyways ^^

**Comment by Pandarix** [comment]
Tested it for both Forge and Fabric and works now. The fix will be in the next update as promised 👋
