### ISSUE TITLE
Duplication of unidentified artifacts

### ISSUE THREAD

**Issue by Saimiau** [Pandarix/BetterArcheology#50]
You can duplicate it in the archeology table if the unidentified artifact is in the container 10 or 11.
Just shift and click on the unidentified artifact, and it will appear on the right part duplicated.
I'm using the version 1.1.5 of the mod for Minecraft 1.20.1 and Forge 47.2.17
![2024-02-16_21 41 24](https://github.com/Pandarix/BetterArcheology/assets/126780415/9f3bd019-c963-4817-860c-6030aed91444)
![2024-02-16_21 41 26](https://github.com/Pandarix/BetterArcheology/assets/126780415/5fcc3ec4-6831-450a-80cb-a575162f8dc0)

**Comment by Pandarix** [comment]
I'll look into this asap. Thank you for reporting in detail!

**Comment by Pandarix** [comment]
Will be fixed in newest Version. I'll upload it very soon ;)
