### ISSUE TITLE
Crash at worldgen

### ISSUE THREAD

**Issue by agentwolf88** [Pandarix/BetterArcheology#51]
Game crash at worldgen.

https://mclo.gs/LKFxRoc

**Comment by Pandarix** [comment]
> java.lang.IllegalAccessError: failed to access class net.minecraft.world.entity.npc.VillagerTrades$TreasureMapForEmeralds from class net.Pandarix.betterarcheology.event.ModEvents

Seems like the accesstransformer.cfg is not properly loaded. It should grant access to the class.
I'll look into it. For replication: Are you using a custom modpack or could you give me a name?

**Comment by Pandarix** [comment]
Could not replicate with Forge 1.20.1 and Betterarcheology alone.
There must be an incompatibility with a mod or other problem within the pack you are using.

**Comment by agentwolf88** [comment]
Better archeology 1.1.5 works great.

**Comment by DelviousCrafts** [comment]
Ran Into this issue as well. Appears to be an incompatibility with Pneumaticcraft, specifically, its amadron tablet list generation for trades. I was able to reproduce with only Better Archeology, Pneumaticcraft, and the required mods installed. Can also confirm this was not an issue in Better Archeology 1.1.5

[Crash report](https://gist.github.com/DelviousCrafts/61cb1f9dee675bc96eaa5ac07d196d92)
[Latest Log](https://gist.github.com/DelviousCrafts/dc5438dd8190fd48741329c14992b723)

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.20
- Better Archeology: 1.1.6
- Patchouli 1.20.1-84
- Pneumaticcraft: 6.0.14
- Yung's API 4.0.4

**Comment by Pandarix** [comment]
Thanks for the hint for the incompatibility! I'll look further into that :)

**Comment by Pandarix** [comment]
It seems like an issue like this already occurred once.
The [AmadronOfferManager](https://github.com/TeamPneumatic/pnc-repressurized/blob/1.20.1/src/main/java/me/desht/pneumaticcraft/common/amadron/AmadronOfferManager.java) from [PneumaticCraft](https://github.com/TeamPneumatic/pnc-repressurized/tree/1.20.1) seems to be the cause of this issue.

Although I don't have enough time to dive deep on this right now and there may be a different cause, I would suggest opening an issue there as the class I linked above already had an issue similar to this one in the past.

Taken from the `getOfferForNullVillager` class inside `AmadronOfferManager.java`:
> creating a fake villager can cause worldgen-related server lockups
> https://github.com/TeamPneumatic/pnc-repressurized/issues/899

**Comment by Pandarix** [comment]
For reference, I've tried using MoreVillagers along with Pneumaticcraft and it seems to work.
Maybe I'll just have to give my TradeRegistration a quick do-over. 😰

**Comment by Pandarix** [comment]
## Fix [1.1.7] is available on:
[![Modrinth](https://img.shields.io/modrinth/v/zCh7omyG?style=flat&logo=modrinth&logoColor=white&label=newest%3A&labelColor=black&color=lime)](https://modrinth.com/mod/better-archeology/version/1.1.7-1.20.1)
[![CurseForge](https://img.shields.io/curseforge/v/835687?style=flat&logo=curseforge&logoColor=white&label=newest%3A&labelColor=black&color=orange)](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files/5158209)
Thank you for reporting!
