### ISSUE TITLE
Soaring Winds Not Doing Anything?

### ISSUE THREAD

**Issue by bforbiggy** [Pandarix/BetterArcheology#56]
From the name, I'd assume the soaring wind's elytra boost would at least give me one extra block of height. I can't tell if it's supposed to be intentional but a slime block with a piston is more effective. Can this be changeable in the config if this is intentional?

Version 1.1.0 is the main version, did test with 1.1.7

**Comment by Pandarix** [comment]
There is a config option for that.
The default of the boost is so low because it would be pretty op to give such a boost. But that is subjective, which is why I added a config option for it.

**Comment by bforbiggy** [comment]
I can't find the config is my issue

![image](https://github.com/Pandarix/BetterArcheology/assets/22730639/d679476b-a903-49e5-8b54-b24f2cdd735f)
