### ISSUE TITLE
1.20.1 Log Spam

### ISSUE THREAD

**Issue by Krimatoria** [Pandarix/BetterArcheology#57]
https://gist.github.com/Krimatoria/1686e211fd4f6f6e79e63451f7cc84c4

**Comment by Pandarix** [comment]
Which version of BetterArcheology & ModLoader are you using?
This message should only be sent once when entering the Titlescreen.

**Comment by Krimatoria** [comment]
> Which version of BetterArcheology & ModLoader are you using? This message should only be sent once when entering the Titlescreen.

betterarcheology-1.1.7-1.20.1.jar
Forge 47.2.7

**Comment by Pandarix** [comment]
This log message should only appear when a new TitleScreen is created. It is mainly used to show that the mixin injection process is working properly and only show the first time, but apparently it does it every time.

Going into different submenus and back or similar creates this logspam. Or maybe a custom menu mod that you were using shows similar behavior.

Anyway, this log message is not essential, I will delete it in the next update.
