### ISSUE TITLE
This mod is not actually here when using neoforge

### ISSUE THREAD

**Issue by krjencik** [Pandarix/BetterArcheology#58]
In Minecraft 1.20.4 (and neo forge 20.4.200) happens this: I install this mod on cf launcher. Entered the game. There  is nothing from this mod. There is no mod like this in the mods tab.

**Comment by Pandarix** [comment]
This seems like the same as Pandarix/BetterArcheology-MultiLoaded#10.
Because Pandarix/BetterArcheology-MultiLoaded#10 is more detailed, I'll be continuing the discussion there.

**Comment by krjencik** [comment]
ok
