### ISSUE TITLE
Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [Pandarix/BetterArcheology#64]
You have outdated structure files in your mod. This causes minecraft to try to update them every time they are loaded, leading to extra memory and cpu usage during worldgen. Please update your structures to match the mc version you are releasing for.

This should be as easy as loading them into game and re-saving them or using a mod to load them into a StructureTemplate and writing them back out to nbt.

**Comment by Pandarix** [comment]
Thank you for reporting that!
I did not know that. I'll do that and close this issue once a new version is out!

**Comment by Pandarix** [comment]
Could you tell me what exactly causes the need for reloading?
Is it just the `DataVersion`?
Because 1.20.1 and 1.20.4 should not have any incompatibilities iirc.

**Comment by Pandarix** [comment]
Just changing the `DataVersion` attrtibute would be way faster for all the jigsaw pieces BA has. 🤔

**Comment by Linguardium** [comment]
yeah. if the actual nbt format didnt change since they were generated, then its just dataversion.

"incompatibilities" are resolved by feeding it through DFU, so while there aren't incompatibilities while using DFU, relying on it through all versions creates more overhead. 

1.20.4's min version appears to be 1.20.2 (data version 3678)
Running the nbt files through DFU to update them would probably be the easiest/quickest way. 

It appears the Minecraft team store their structures as snbt and update them at datagen

**Comment by Pandarix** [comment]
Thank you so much for your kind and constructive help! The fix will be out soon.

Do you happen to think there might be a connection between this problem and #61 and maybe even #59? You seem to know more about NBT related issues than I do ^^'.
