### ISSUE TITLE
Crash mesa_ruins

### ISSUE THREAD

**Issue by spirow06** [Pandarix/BetterArcheology#67]
Hello, I was playing on a server with friends and when one of them approached a mesa and one of the mod's structures, the server crashed. As soon as he tries to reconnect, the server crashes again.
So I deleted the said structure and the problem was solved. We obviously hid the problem under the rug :p. I hope you can help me.
Im using forge 47.2.14 minecraft 1.20.1.

[crash.txt](https://github.com/Pandarix/BetterArcheology/files/15082123/crash.txt)
[logs serv IV.txt](https://github.com/Pandarix/BetterArcheology/files/15082127/logs.serv.IV.txt)

Here are my latest.log and crash log

**Comment by Xalveris** [comment]
Having the same issue. I tried to pregenerate some chunks with another mod and it hit a mesa ruin and crashed.
[crash-2024-04-23_16.59.24-server.txt](https://github.com/Pandarix/BetterArcheology/files/15084314/crash-2024-04-23_16.59.24-server.txt)
[latest.log](https://github.com/Pandarix/BetterArcheology/files/15084315/latest.log)

**Comment by Pandarix** [comment]
This might be caused by the Waterlogprocessor that is used. I'll look into that, sorry for the inconvenience!

**Comment by Pandarix** [comment]
The Waterlogprocessor is not part of the structure_processors for the Mesa Ruins. There must be an incompatibility with a mod.

**Comment by Pandarix** [comment]
@Xalveris I tried to replicate your issue specifically because I could explicitly see you're using the IndustrialVillage Modpack.
I've installed it and tested 3 different Mesa Ruins. Haven't gotten a crash yet.

**Comment by Pandarix** [comment]
Testing the Modpack with Mesa Ruins spawning at the bottom of the ocean and still no error :/
![2024-05-11_14 47 02](https://github.com/Pandarix/BetterArcheology/assets/98489042/361b0a82-b851-4cbe-a7a0-9892d731e920)

I also looked through every `nbt` file of the structures and there isn't a single one except the mesa ruins containing the `{minecraft:wither_skeleton_skull}` from your crashes.

**Comment by Xalveris** [comment]
The modpack was updated a few days ago which must have fixed whatever incompatibility was causing it then. Thanks for taking the time to investigate the problem!

**Comment by Pandarix** [comment]
Alright! Thanks for reporting nonetheless :).
