### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by PukPukov** [Pandarix/BetterArcheology#68]

**Comment by Pandarix** [comment]
It is definitely planned, but the mod depends on Yung's API, which is currently not updated to 1.20.6.
Contact them or please be patient.

**Comment by PukPukov** [comment]
1.21 is out, and YUNG's API will skip 1.20.6, so I think this issue should be changed to 1.21.

**Comment by Pandarix** [comment]
1.21 sadly has some breaking changes for enchantments that I'll have to look into further than I'm currently able to.
I'll get to the update as soon as I'm finished with uni and erasmus-stuff.
Sorry for the wait!

**Comment by Pandarix** [comment]
## Ported version is out now!

### Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions?g=1.21) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files/all?version=1.21)
Please wait until CurseForge has verified the files :)
