### ISSUE TITLE
Suggestion Evoker Trap

### ISSUE THREAD

**Issue by QwertRvg** [Pandarix/BetterArcheology#72]
Hey, could you make the Evoker Trap at least drop when mined?
Would be cool, even if they couldn't get crafted.

**Comment by Pandarix** [comment]
I thought they could get too powerful initially. But I agree that they should be obtainable.
This might just be added in the next update. I'm keeping you posted!

**Comment by QwertRvg** [comment]
thanks a lot!

**Comment by Pandarix** [comment]
Update is out now:
[![Modrinth](https://img.shields.io/modrinth/v/zCh7omyG?style=flat&logo=modrinth&logoColor=forestgreen&label=newest%3A&labelColor=black&color=forestgreen)](https://modrinth.com/mod/better-archeology)
[![CurseForge](https://img.shields.io/curseforge/v/835687?style=flat&logo=curseforge&logoColor=orangered&label=newest%3A&labelColor=black&color=orangered)](https://www.curseforge.com/minecraft/mc-mods/better-archeology)

**Comment by QwertRvg** [comment]
great, thanks so much!
