### ISSUE TITLE
You broke something -_-

### ISSUE THREAD

**Issue by Zelioth** [Pandarix/BetterArcheology#73]
Minecraft 1.20.1
Forge 47.2.31
Better Archeology 1.1.9 (Released today) 

[crash-2024-05-13_23.05.20-client.txt](https://github.com/Pandarix/BetterArcheology/files/15302435/crash-2024-05-13_23.05.20-client.txt)

client doesn't open when mod is installed. removing mod or downgrading fixes issue

**Comment by Pandarix** [comment]
Oh god, I'm sorry for not testing enough. I'll work on a direct compatibility for Alex's Mobs instead of a workaround immediately!

**Comment by Pandarix** [comment]
I will archive the broken 1.1.9 version and now upload the fixed version.
Please close this issue if this resolves the errors. I've tested the fix with Alex's Mobs and without it. This time is seems to work smoothly.

Again, sorry for the inconvenience!

**Comment by Pandarix** [comment]
Update is out now:
[![Modrinth](https://img.shields.io/modrinth/v/zCh7omyG?style=flat&logo=modrinth&logoColor=forestgreen&label=newest%3A&labelColor=black&color=forestgreen)](https://modrinth.com/mod/better-archeology/version/8f9j7B3i)
[![CurseForge](https://img.shields.io/curseforge/v/835687?style=flat&logo=curseforge&logoColor=orangered&label=newest%3A&labelColor=black&color=orangered)](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files/5343082)

**Comment by Zelioth** [comment]
Hey, Thanks for the speedy update. I tested and can confirm it works. What is strange though is I don't even have Alex Mobs installed on my mod pack. Friends United 2.0. The crash started after updating so I figured it was caused by a new compatibility issue or something but regardless its fixed now. Thank you :D
