### ISSUE TITLE
Enchants for the Brush

### ISSUE THREAD

**Issue by toffi3** [Pandarix/BetterArcheology#74]
Hi, it's a great mod but have you ever thought about adding enchants for brush like making it brush sand and gravel faster because i myself find it annoying that the process of brushing is so slow and i can't finfd myself a mod that would make it. Just a sugesstion

**Comment by Pandarix** [comment]
There was a bug where the upgraded brushes did not brush faster. I forgot to replace some values ^^'.
Also, in the next update there will be a netherite brush (as requested on CF). That one will definitely suffice :).
Sorry for the late response!

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
