### ISSUE TITLE
Identified Artifacts Missing Texture [Forge 1.20.1]

### ISSUE THREAD

**Issue by arcticgalaxies** [Pandarix/BetterArcheology#75]
The identified artifacts are missing textures, they show up for me as the black enchanted black and purple missing texture tiles

**Comment by Pandarix** [comment]
What version of BA are you playing on? What Modloader are you using? Do you have CIT installed?

**Comment by arcticgalaxies** [comment]
oh jeez i didnt get a notification for this, sorry!

forge 1.20 at launcher and no, i dont

should i try cit?

**Comment by Pandarix** [comment]
Closed due to inactivity
