### ISSUE TITLE
Need More Config

### ISSUE THREAD

**Issue by DarkFighter5000** [Pandarix/BetterArcheology#76]
I like the concept of the mod and I want to use it in my modpack to enhance the archeology aspect of the game, however some aspects of the mod don't quite fit my vision & I need more config options to deal with them. A toggle for certain drops like the totems or the broken bomb would be neat! Or a way to edit loot tables would do the same I guess? Maybe a toggle to turn off specific skeleton abilities too?
I'm not sure what the creeper skeleton does if anything but other vise those might be just fine, the greater issue is the totems, don't get me wrong they are cool and all but they don't fit the theme I'm going for.

I doubt the version matters but here is it anyways: Better Archeology 1.1.9 for 1.20.1 [FABRIC]

**Comment by Pandarix** [comment]
I currently have a different Mod WIP and there I'm experimenting with almost full configuration. I'm also all for the options you suggested.
Right now, I'm caught up with uni-stuff but I'll get to reworking the config system and adding options as soon as I can :).

**Comment by Pandarix** [comment]
Currently, I have added a lot of new Config options but the library I'm using has an issue with String values (e.g. a comma-separated List of Items that would be needed for options mentioned in Pandarix/BetterArcheology-MultiLoaded#9 ).
I've created a [pull-request that would fix that issue](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/pull/24) and if that fix gets merged, I'll be able to add that too :).

**Comment by DarkFighter5000** [comment]
Cool, thanks for taking time to reply!

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
