### ISSUE TITLE
Totem of radiance not damaging hostile entities

### ISSUE THREAD

**Issue by extrememine1** [Pandarix/BetterArcheology#78]
I have set tick speeds to high rates and tested multiple times on both multiplayer and singleplayer and totem of radiance doesn't damage hostile mobs at all
![Screenshot 2024-06-27 220826](https://github.com/Pandarix/BetterArcheology/assets/174029659/c0d365a6-266a-4f9e-8e8e-56ca2a069114)

**Comment by Pandarix** [comment]
This will be fixed in the next update.
I've had a lot of personal business due to uni lately, but now I have time to release a new version including this fix soon :). Please be patient

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
