### ISSUE TITLE
 null check in the soaring winds artifacts enchantment

### ISSUE THREAD

**Issue by munstarz** [Pandarix/BetterArcheology#79]
https://mclo.gs/KF89aIA

caused crash during liftoff

**Comment by Pandarix** [comment]
This part of the code should only be called if you have Trinkets installed. I assume you have installed it, otherwise please tell me because that means there is a different issue here.
There is a null reference where there shouldn't be one - anyway: it is my fault for not doing a safety check there.
Does this error come up every time you are using an Elytra with Soaring Winds, or does this only happen occasionally?

**Comment by munstarz** [comment]
Hello:


I do have trinkets installed. Thanks for letting me know about it! It was only triggered when I try to take off using an elytra. I didn't use an elytra with said enchantment ever after that, I am not entirely sure if I try to do so again would it also cause a crash. Anyways, thank you for the reply.


Munsters
&nbsp;





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年7月13日(星期六) 晚上11:35
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Pandarix/BetterArcheology]  null check in the soaring winds artifacts enchantment (Issue #79)














 
This part of the code should only be called if you have Trinkets installed. I assume you have installed it, otherwise please tell me because that means there is a different issue here.
 There is a null reference where there shouldn't be one - anyway: it is my fault for not doing a safety check there.
 Does this error come up every time you are using an Elytra with Soaring Winds, or does this only happen occasionally?

**Comment by Pandarix** [comment]
I added a null and additional safety checks to be safe.
I've had a lot of personal business due to uni lately, but now I have time to release a new version including this fix soon :). Please be patient

**Comment by munstarz** [comment]
Hey:

Please take your time~ the mod is working quite fine without the elytra too!
Good luck on exams and studies and thanks Xoxo.


Jiawen




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月25日(星期四) 凌晨1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Pandarix/BetterArcheology]  null check in the soaring winds artifacts enchantment (Issue #79)





 
I added a null and additional safety checks to be safe.
 I've had a lot of personal business due to uni lately, but now I have time to release a new version including this fix soon :). Please be patient
 
&mdash;

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
