### ISSUE TITLE
Tunneling w/ Silk Touch only applies Silk Touch to top block

### ISSUE THREAD

**Issue by 1xBluee** [Pandarix/BetterArcheology#80]
Whenever I use the tunneling enchantment with Silk Touch say two stone blocks, I will be returned with a stone block and a cobblestone block.

https://github.com/Pandarix/BetterArcheology/assets/109627294/fac7f434-57e7-4cc7-99d1-e8b3c9a92092

**Comment by Pandarix** [comment]
This is due to the way the block below gets broken. I'll look into a way to apply enchantments on the break mechanic. Sorry for the inconvenience!

**Comment by Pandarix** [comment]
Found a workaround that actually is way better in every way.
I've had a lot of personal business due to uni lately, but now I have time to release a new version including this fix soon :). Please be patient

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
