### ISSUE TITLE
Tunneling can't be applied to axes or hoes

### ISSUE THREAD

**Issue by SageofTurtles** [Pandarix/BetterArcheology#82]
Pretty much the title.  I tried applying the Tunneling enchantment from an enchanted book to several items, and it could only be applied to pickaxes and shovels, but not axes or hoes.  Not sure if this is an intended feature, but my Enchanted ToolTips mod seems to think it should be applicable to all tools so I wanted to report it in case it's a bug.  Using Fabric for Minecraft 1.20.1 and Better Archeology 1.1.9.

**Comment by Pandarix** [comment]
This is an intended feature. I could see the application with hoes (although they are already pretty fast at the blocks they're efficient at anyway) but not really with axes.
The text from the Enchanted ToolTips mod is written in the lang file of this mod, therefore my error.

Would you be satisfied with a change of documentation, or do you think that making the enchantment accessible to axes and hoes would be a benefit?

**Comment by SageofTurtles** [comment]
I would personally consider it a benefit when "tunneling" through blocks not typically found underground in vanilla, such as nether wart blocks or densely-packed logs. Although maybe this would be better as a configurable option in a future release. Short of that, possibly just updating the tooltip for clarity would be nice.

Just my opinion. This obviously isn't a major issue, I've just been looking at compatibility between my mods and wanted to make mention of it.

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
