### ISSUE TITLE
1.20.1 ExplorationMapFunction

### ISSUE THREAD

**Issue by Krimatoria** [Pandarix/BetterArcheology#84]
I run the build in one mod to clean up errors in the logs. And I noticed that an error appears when adding your mod. With other mods, when it is turned off, it does not occur.

[13:25:26] [Worker-ResourceReload-0/ERROR] [minecraft/ExplorationMapFunction]: Error while parsing loot table decoration entry. Found jungle_temple. Defaulting to MANSION
[13:25:26] [Worker-ResourceReload-0/ERROR] [minecraft/ExplorationMapFunction]: Error while parsing loot table decoration entry. Found jungle_temple. Defaulting to MANSION

![image](https://github.com/user-attachments/assets/caaf8c1b-ea6e-4d35-9906-404fbf3f5fd6)
betterarcheology-1.1.9-1.20.1.jar

**Comment by ginsm** [comment]
This is occurring for me as well.

**Comment by Pandarix** [comment]
Sorry about this issue. Does this affect your game in any way?
I've used a tool to generate the .json files for the exploration maps. Apparently, there are some unsupported marker types in there. I'll change jungle_temple to mansion then in the next update to avoid this error.

**Comment by Krimatoria** [comment]
> Извините за эту проблему. Это как-то влияет на вашу игру? Я использовал инструмент для генерации файлов .json для карт исследования. По-видимому, там есть некоторые неподдерживаемые типы маркеров. Я изменю jungle_temple на mansion в следующем обновлении, чтобы избежать этой ошибки.

I haven't got to archaeology yet, I haven't found the fragments of the artifact. I'll send a screenshot later)

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
