### ISSUE TITLE
Totem of Torrents for use with elytra

### ISSUE THREAD

**Issue by zwamdurkel** [Pandarix/BetterArcheology#85]
**This is a suggestion**

I've been using the Totem of Torrents with my elytra as an infinite firework rocket, which works surprisingly well.

But because the added velocity is calculated partially by subtracting the current velocity from the rotation vector, it tends to do nothing or even appear to slow you down in some cases where the player is flying fast to begin with or if the player has a large vertical (y) velocity. 

It might not be the intended use case of the item, but I think it would be cool if it worked better while using an elytra. It would also be helpful if the y velocity also gets a boost. I think this would make the item more useful as its standard usecase is not very useful for my play style.

**Comment by Pandarix** [comment]
The next update will include a lot of config options and before you actually commented, I already implemented separate values for x and y boosting with the totem. So the problem you are describing should be fixed once the new update is out and can be easily configured :).
Thanks for the constructive feedback!

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)
