### ISSUE TITLE
(request) Make skulls wearable in helmet slot

### ISSUE THREAD

**Issue by Kelpiesaurus** [Pandarix/BetterArcheology#86]
Hello. Thank you for creating such a fun and beautifully designed mod! The one thing I can think of that could make it any better would be the ability to wear the chicken, creeper, wolf, ocelot, sheep, villager and guardian skulls in the helmet armor slot just like we can with skeleton skulls. I understand if that may be too much of a hassle or out of the scope of the mod, but if not, it would be a pretty cool bonus feature.

**Comment by Pandarix** [comment]
I actually put a display model for almost every skull block anyways, so that would be no problem. And as it turns out, the code for making them equippable for the head is insanely easy. Soo, I already implemented it and it should be included in the next update along a lot of other small fixes :).
Thank you for you feedback!

**Comment by Pandarix** [comment]
## Fix/ Feature is now out in BetterArcheology 1.2.0!

This issue will be closed. If the problem still persists or similar, feel free to reopen this issue.

## Links
[![Modrinth Downloads](https://img.shields.io/modrinth/dt/better-archeology?style=flat&logo=modrinth&link=https%3A%2F%2Fmodrinth.com%2Fmod%2Fbetter-archeology%2Fversions)](https://modrinth.com/mod/better-archeology/versions) [![CurseForge Downloads](https://img.shields.io/curseforge/dt/835687?style=flat&logo=curseforge&logoColor=orange&color=orange)
](https://www.curseforge.com/minecraft/mc-mods/better-archeology/files)
Please wait until CurseForge has verified the files and wait for the 1.2.0 :)

**Comment by Kelpiesaurus** [comment]
Thank you so much for implementing this! It turns out the chicken skull is too small and only a bit of the beak pokes out, but the the others fit well enough and the sheep skull is my favorite :)
![sheep_skull](https://github.com/user-attachments/assets/b9f150af-d768-4735-b0e7-325a457f1928)
