### ISSUE TITLE
enchant tunneling issue

### ISSUE THREAD

**Issue by xxvalou77** [Pandarix/BetterArcheology#96]
enchant tunneling breaking to the bedrock
![image_2024-09-23_175756408](https://github.com/user-attachments/assets/12f853b7-aa0e-4638-b642-f9df1b8a3584)

**Comment by Pandarix** [comment]
This issue has already been fixed in version 1.2.1.
Please tell me if the issue persists after updating or not :)!

**Comment by xxvalou77** [comment]
thanks sorry the mods in the server wasnt updated but on the client yeah
